### ISSUE TITLE
Es werden keine EMH Zähler ausgelesen

### ISSUE THREAD

**Issue by Michaelstru** [elueckel/Discovergy_Smartmeter#10]
Hi eluecke, ich habe das Problenm das keine aktuelle Leistung EMH Zähler ausgelesen werden , die Zäler von ESY und die Gaszähler bekomme ich ohne weiteres ausgelesen

**Comment by elueckel** [comment]
Hi,
Bitte schicke mal was übermittelt wird. Die hatten eine Änderung … evtl ist das das Problem ?

Enno

**Comment by Michaelstru** [comment]
Hi Enno, stehe gerade mit Discovergy in Kontakt er wollte ganz gerne das ich diesen Issure aufmache, also es kann sein das sich der Mitarbeiter von Discovergy sich hier noch mit einklinkt. Bin gerade unterwegs, ich meine das da hauptsächlich die aktuelle Leistung fehlt. 

Vg 
Michael


Alte Schmiedestr. 5d | 27449 Kutenholz
Telefon: 04762 / 31 73 23
Mobil: 0151 / 29 11 61 00

www.strubenhoff.de

**Comment by zoernert** [comment]
Beim Blick in den Code ist mir aufgefallen, dass versucht wird auf Basis des Herstellers des Zählers (hier EMH) eine Indikation zu bekommen, welche Felder verfügbar sind. Das wird schiefgehen, wenn man nicht über den `/field_names` Endpunkt die Felder abruft/validert.

**Comment by elueckel** [comment]
Hi @Michaelstru  
hast du mal im Portal geschaut ob überhaupt was kommt? Ich hatte letztens auch den Effekt das überhaupt nix kam. Ansonsten mal den Zähler sharen und ich kann mal gucken.

@zoernert gibt es die Fieldnames schon länger ... macht Sinn, aber da müsste ich mal einiges umbauen. 

Hast du mal Zeit/Lust wegen einer Integration in corrently zu sprechen. Ich bin ja inzwischen auch Kunde und ich denke es gäbe bestimmt einige spannende Themen?

**Comment by Michaelstru** [comment]
Hi elueckel,
![EMH Abfrage](https://user-images.githubusercontent.com/96476448/147002702-496faf99-f784-4b2e-b487-f85723f55163.png)
Zugriff auf dem Zähler hast Du ja bereits.
VG Michael
hier mal das Ergebnis der Abfrage

**Comment by Michaelstru** [comment]
Daten aus dem Portal
<img width="907" alt="image" src="https://user-images.githubusercontent.com/96476448/147003117-6619e255-7e54-43af-8fd3-4ae1ffbde5e1.png">

**Comment by zoernert** [comment]
> Hast du mal Zeit/Lust wegen einer Integration in corrently zu sprechen. Ich bin ja inzwischen auch Kunde und ich denke es gäbe bestimmt einige spannende Themen?

Gerne => Einfach melden ... +49 6226 9680091


Zum Thema:
Ja, das Problem mit den field_names vorher einlesen habe ich auch bereits gesehen. Ein Quickfix dürfte aber auch eine Möglichkeit sein - Aktuell im Code Zeile 333ff .  @Michaelstru Bitte einmal msb@stromdao.com einladen zum Zähler, dann mach ich die Anpassung direkt und stelle sie als PR ein.

**Comment by Michaelstru** [comment]
bist eingeladen

**Comment by zoernert** [comment]
Habe es hinbekommen. mit der Idee des Quick und Dirty Fixes (9.25 OBIS Code) .

PR kommt gleich.

**Comment by Michaelstru** [comment]
Moin, damit läuft es bei mir auch :-)

**Comment by Michaelstru** [comment]
Es mach aber mehr Sinn nicht 9.25 sondern 1.25 abzufragen, da 1.25 die Wirkleistung ist und 9.25 die Scheinleistung ist. Dann stimmen auch die Daten mit dem Portal überein.

**Comment by elueckel** [comment]
@Michaelstru es gibt eine neue BETA die jetzt 1.25 bereitstellt. 

@zoernert der interne Aufbau ist auch neu und basiert jetzt auf den Field_Names ... wder scaling faktor ist noch ein Rätsel für mich, da er bei mir 1 ist und bei einem anderen EMH Zähler 80

**Comment by Michaelstru** [comment]
Danke, wenn ich versuche mir die Beta zu installieren bekomme ich immer die 2.13 Version, Ich muss dann die Beta Files manuell in das Modul-Verzeichnis kopieren, dann geht es und ich bekomme alle Werte angezeigt.

**Comment by elueckel** [comment]
Entweder im Module Store auf Beta setzen oder in der modul Erweiterung

**Comment by Michaelstru** [comment]
Danke so geht's ;-)
