### ISSUE TITLE
Keine Spannungsanzeige (ESY)

### ISSUE THREAD

**Issue by ghost** [elueckel/Discovergy_Smartmeter#5]
Moin,

ich bekomme keine Spannungsanzeige auf allen 3 Phasen.  
Fehlermeldung beim Einrichten:
<br />
<b>Notice</b>:  Undefined property: stdClass::$voltage1 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>382</b><br />
<br />
<b>Notice</b>:  Undefined property: stdClass::$voltage2 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>387</b><br />
<br />
<b>Notice</b>:  Undefined property: stdClass::$voltage3 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>392</b><br />

Typ ESY, montiert im März 2018.
Meldung im IP-Symcon Statuslog:
19.01.2021, 13:33:05 | TimerPool            | Strom (GetMeterReading): <br />
<b>Notice</b>:  Undefined property: stdClass::$voltage1 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>382</b><br />
<br />
<b>Notice</b>:  Undefined property: stdClass::$voltage2 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>387</b><br />
<br />
<b>Notice</b>:  Undefined property: stdClass::$voltage3 in <b>/var/lib/symcon/modules/.store/elueckel.discovergy/Discovergy_Smartmeter/module.php</b> on line <b>392</b><br />

**Comment by elueckel** [comment]
Hi,
funktioniert denn sonst alles? Ich habe auch ESY Zähler und keine Probleme. Gibt es sonst Auffälligkeiten - ging es mal?

**Comment by ghost** [comment]
Ja, sonst funktioniert alles. Aktueller Verbrauch, auch auf den einzelnen Phasen, Kostenberechnung etc. Die Installation ist ganz frisch, auch die Symcon-Installation (V5.5) ist von Dez. 2020. Gas funktioniert auch einwandfrei. Ok, ein paar weniger Variablen. Das ganze läuft unter Ubuntu 18.04.5.

**Comment by elueckel** [comment]
Gib mal bitte https://api.discovergy.com/public/v1/last_reading?meterId=  ein ... also hinten Deine Zähler ID einfügen. Da kommt dann ein JSON File ... das bitte mal posten. Ansonsten schau mal was bei POWER 1 - 3 kommt.

**Comment by ghost** [comment]
Hier die Rohdaten: {"time":1611084249298,"values":{"power":1247220,"power3":611750,"energyOut":11698300000,"power1":48930,"energy":238496673914000,"power2":586540}}

**Comment by elueckel** [comment]
Es gibt anscheinend Unterschiede bei den esy Zählern. Ein neues Update unter Beta sollte es beheben.

**Comment by ghost** [comment]
Die Fehlermeldungen sind weg. Aber Phase 1 und Phase 2 zeigen den selben aktuellen Verbrauch (den von Phase 1). Phase 3 ist ok. Spannung ist auf allen 3 Phasen = 0, ist ja aber auch logisch, wenn der Zähler dafür keine Daten liefert. Der Rest sieht soweit gut aus.
Gibt es eine Möglichkeit, statt 0,0 V eine(n) Wert / Text anzuzeigen, der deutlich macht, das der Zähler keine Werte liefert? Oder die Variablen nicht anzulegen beim Erstellen der Instanz?
